version: '3.3'

services:
  lb:
    build:
      context: ./nginx_config
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - service1
      - service2
      - service3
  service1:
    build:
      context: ./uuid-generator
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_ID=1
    networks:
      - app-network
  service2:
    build:
      context: ./uuid-generator
    ports:
      - "8082:8080"
    environment:
      - INSTANCE_ID=2
    networks:
      - app-network
  service3:
    build:
      context: ./uuid-generator
    ports:
      - "8083:8080"
    environment:
      - INSTANCE_ID=3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge